Repository nesbox/TIC-80, pull requests merged in 2024-05, with the labels that each got.

#2553 SDL: don't ignore briefly pressed keys
  src/system/sdl/main.c
Labels: bug

#2567 Fix `surf` on win32 builds
  src/studio/system.h
Labels: bug

#2579 adds gamepad state being reset
  src/core/core.c
Labels: bug

#2581 #1950: added 'devmode: on' metatag to disable game menu
  src/studio/studio.c
Labels: enhancement

#2585 Readme improvements for Windows
  README.md
Labels: documentation

#2587 #2584: add 'of' js keyword
  src/api/js.c
Labels: lang: javascript

#2594 Hotkeys topic in help
  src/studio/screens/console.c
Labels: console

#2593 Fix for Arrow keys not working on android.
  build/android/app/src/main/java/org/libsdl/app/SDLActivity.java
Labels: platform: android
